version: '3.1'

networks:
  basic:
  #driver: bridge
  #      config:
  #        - subnet: 172.66.1.0/24
  #    ipam:
  #      driver: default
  #      config:
  #        - subnet: 172.66.1.0/24
services:
  bitesla-service-api:
    image: bitesla-service-api
    build: ./service/service-api
    container_name: bitesla-service-api
    command: --registry_address=bitesla-consul:8500
    ports:
      - 8090:8090
#    environment:
#      NET: "host"
    depends_on:
      - bitesla-consul
    links:
      - bitesla-mysql
    networks:
      - basic

  bitesla-service-user:
    image: bitesla-service-user
    build: ./service/service-user
    container_name: bitesla-service-user
    command: --registry_address=bitesla-consul:8500
#    ports:
#      - 50001:50001
#    environment:
#      DB_NAME: "mysql"
#      DB_HOST: "mysql"
#      DB_PORT: "3306"
#      DB_USER: "root"
#      DB_PASSWORD: "123456"
#      REDIS_ADDR: "redis:6379"
#      REDIS_PWD: ""
    networks:
      - basic
    depends_on:
      - bitesla-consul

  bitesla-service-exchange:
    image: bitesla-service-exchange
    build: ./service/service-exchange
    container_name: bitesla-service-exchange
    command: --registry_address=bitesla-consul:8500
    networks:
      - basic
    depends_on:
      - bitesla-consul

  bitesla-service-strategy:
    image: bitesla-service-strategy
    build: ./service/service-strategy
    container_name: bitesla-service-strategy
    command: --registry_address=bitesla-consul:8500
    networks:
      - basic
    depends_on:
      - bitesla-consul

  bitesla-service-trader:
    image: bitesla-service-trader
    build: ./service/service-trader
    container_name: bitesla-service-trader
    command: --registry_address=bitesla-consul:8500
    networks:
      - basic
    depends_on:
      - bitesla-consul

  bitesla-mysql:
    image: mysql:5.7
    container_name: bitesla-mysql
    volumes:
      - $BUILD_PATH/bitesla-server/mysql/data:/var/lib/mysql
      - $BUILD_PATH/bitesla-server/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=wuj123
      # 时区，默认差8小时
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
    networks:
      - basic

  bitesla-redis:
    container_name:  bitesla-redis
    ports:
      - 6379:6379
    image: redis
    volumes:
      - $BUILD_PATH/bitesla-server/redis/conf/redis.conf:/etc/redis/redis.conf
      - $BUILD_PATH/bitesla-server/redis/data:/data
    networks:
      - basic
    command: redis-server --requirepass wuj123

  bitesla-consul:
    image: progrium/consul:latest
    container_name: bitesla-consul
#    environment:
#      NET: "host"
    command: -ui-dir /ui -server -bootstrap
    networks:
      - basic
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 53:53/udp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500"]
      interval: 5s
      timeout: 5s
      retries: 3